---
- name: workflow1
  hosts: all
  tasks:
    - name: do something simple that doesnt fail
      debug: 
        msg: like displaying a message

    - name: set stats for next workflow to consume
      set_stats:
        data:
          job_status: success
      register: stats

    - name:
      debug:
        var: stats
